name: macOS

on: [push]

jobs:
  build:
    env:
      PACKAGE_NAME: _PACKAGE_NAME

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode 11.4
      run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test -v --enable-code-coverage
